[package]
name           = "azure_sdk_for_rust"
version        = "0.6.0"
description    = "Rust wrappers around Microsoft Azure REST APIs"
readme         = "README.md"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>", "Dong Liu <doliu@microsoft.com>"]
license        = "Apache-2.0"
repository     = "https://github.com/MindFlavor/AzureSDKForRust"
documentation  = "http://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust/index.html"
homepage       = "https://github.com/MindFlavor/AzureSDKForRust"

keywords       = ["sdk", "azure", "rest", "iot", "cloud"]
categories     = ["api-bindings"]

[dependencies]
RustyXML       = "*"
base64         = "*"
chrono         = "*"
env_logger     = "*"
futures        = "*"
hyper          = "*"
hyper-tls      = "*"
log            = "*"
mime           = "*"
native-tls     = "*"
quick-error    = "*"
rust-crypto    = "*"
serde          = "*"
serde_derive   = "*"
serde_json     = "*"
time           = "*"
tokio          = "*"
tokio-core     = "*"
url            = "*"
uuid           = "*"

[features]
test_e2e       = []
