(function() {var implementors = {};
implementors["azure_sdk_for_rust"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"azure_sdk_for_rust/azure/core/range/struct.Range.html\" title=\"struct azure_sdk_for_rust::azure::core::range::Range\">Range</a>&gt; for <a class=\"struct\" href=\"azure_sdk_for_rust/azure/core/ba512_range/struct.BA512Range.html\" title=\"struct azure_sdk_for_rust::azure::core::ba512_range::BA512Range\">BA512Range</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt; for UniCase&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>&gt;","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt; for UniCase&lt;&amp;'a <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for Level","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html\" title=\"struct alloc::vec::Vec\">Vec</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt;&gt; for <a class=\"struct\" href=\"https://docs.rs/tokio-core/0.1/tokio_core/io/frame/struct.EasyBuf.html\" title=\"struct tokio_core::io::frame::EasyBuf\">EasyBuf</a>","impl&lt;B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"enum\" href=\"https://docs.rs/tokio-proto/0.1/tokio_proto/streaming/message/enum.Message.html\" title=\"enum tokio_proto::streaming::message::Message\">Message</a>&lt;__ProtoResponse, B&gt;&gt; for <a class=\"struct\" href=\"https://docs.rs/hyper/0.11.1/hyper/http/response/struct.Response.html\" title=\"struct hyper::http::response::Response\">Response</a>&lt;B&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
